version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/static-site/portfolio_camille"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" 